/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import controller.Controller;
import controller.ServerManager;
import controller.ServerState;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import threads.ServerThread;

/**
 *
 * @author lukaa
 */
public class ServerForm extends javax.swing.JFrame {
    private ServerManager serverManager = new ServerManager();
    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        setLocationRelativeTo(null);
        lblStatus.setVisible(false);
        lblStatus.setText("Server je ugasen!");
        btnPokreniServer.setVisible(false);
        btnZaustaviServer.setVisible(false);
        setTitle("Serverska forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPokreniServer = new javax.swing.JButton();
        btnZaustaviServer = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBrojKlijenata = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        meniIzmeniKonf = new javax.swing.JMenu();
        meniIzmeni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPokreniServer.setText("Pokreni server");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        btnZaustaviServer.setText("Zaustavi server");
        btnZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviServerActionPerformed(evt);
            }
        });

        lblStatus.setText("Serverski status");

        jLabel1.setText("Unesite max broj klijenata:");

        txtBrojKlijenata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBrojKlijenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojKlijenataActionPerformed(evt);
            }
        });
        txtBrojKlijenata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrojKlijenataKeyPressed(evt);
            }
        });

        meniIzmeniKonf.setText("Konfiguracija baze");

        meniIzmeni.setText("Izmeni konfiguraciju");
        meniIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniIzmeniActionPerformed(evt);
            }
        });
        meniIzmeniKonf.add(meniIzmeni);

        jMenuBar1.add(meniIzmeniKonf);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrojKlijenata, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZaustaviServer)
                            .addComponent(btnPokreniServer))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBrojKlijenata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(lblStatus)
                .addGap(31, 31, 31)
                .addComponent(btnPokreniServer)
                .addGap(18, 18, 18)
                .addComponent(btnZaustaviServer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meniIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniIzmeniActionPerformed
        BaseConfiguration bc = new BaseConfiguration(this, true);
        bc.setVisible(true);
    }//GEN-LAST:event_meniIzmeniActionPerformed

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        try {
            int max = Integer.parseInt(txtBrojKlijenata.getText());
            ServerState.getInstance().setMaxKlijenata(max);
            serverManager.startServer(max);
            btnPokreniServer.setEnabled(false);
            btnZaustaviServer.setEnabled(true);
            lblStatus.setText("Server je pokrenut");
            JOptionPane.showMessageDialog(this, "Server pokrenut");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviServerActionPerformed
        if (serverManager.getServerThread() != null) {
            serverManager.stopServer();
            ServerState.getInstance().setMaxKlijenata(0);
            JOptionPane.showMessageDialog(this, "Server je ugasen");
            lblStatus.setText("Server je ugasen!");
            btnPokreniServer.setEnabled(true);
            btnZaustaviServer.setEnabled(false);
        }
    }//GEN-LAST:event_btnZaustaviServerActionPerformed

    private void txtBrojKlijenataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrojKlijenataKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            lblStatus.setVisible(true);
            btnPokreniServer.setVisible(true);
            btnZaustaviServer.setVisible(true);
            btnZaustaviServer.setEnabled(false);
        }
    }//GEN-LAST:event_txtBrojKlijenataKeyPressed

    private void txtBrojKlijenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojKlijenataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojKlijenataActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuItem meniIzmeni;
    private javax.swing.JMenu meniIzmeniKonf;
    private javax.swing.JTextField txtBrojKlijenata;
    // End of variables declaration//GEN-END:variables
}