/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Citalac;
import model.Iznajmljivanje;
import model.StavkaIznajmljivanja;
import modeliTabele.ModelTabeleStavkaIzn;

/**
 *
 * @author lukaa
 */
public class DetaljiIznajmljivanje extends javax.swing.JFrame {

    private ModelTabeleStavkaIzn modelTabele;
    private Iznajmljivanje iznajmljivanje;
    private Citalac citalac;
    private int poslednjeSelektRed = -1;
    /**
     * Creates new form DetaljiIznajmljivanje
     */
    public DetaljiIznajmljivanje(Iznajmljivanje iznajmljivanje) {
        initComponents();
        this.iznajmljivanje = iznajmljivanje;
        this.citalac = iznajmljivanje.getCitalac();
        this.modelTabele = new ModelTabeleStavkaIzn();
        
        popuniComboboxCitaoci();
        
        List<StavkaIznajmljivanja> listaStavki = Controller.getInstance().vratiSveStavkeIznajmljivanja(iznajmljivanje);
        System.out.println("BROJ STAVKI : " + listaStavki);
        modelTabele.setListaStavki(listaStavki);
        podesiTabelu(modelTabele);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jLabelCitalac = new javax.swing.JLabel();
        jButtonPromeniCitaoca = new javax.swing.JButton();
        jComboBoxCitaoci = new javax.swing.JComboBox<>();
        jButtonSacuvajCitaoca = new javax.swing.JButton();
        jButtonPromeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jLabelCitalac.setText("CItalac: ");

        jButtonPromeniCitaoca.setText("Promeni");
        jButtonPromeniCitaoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniCitaocaActionPerformed(evt);
            }
        });

        jButtonSacuvajCitaoca.setText("Sacuvaj");
        jButtonSacuvajCitaoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajCitaocaActionPerformed(evt);
            }
        });

        jButtonPromeni.setText("Promeni");
        jButtonPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCitalac)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCitaoci, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPromeniCitaoca)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSacuvajCitaoca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonObrisi)
                            .addComponent(jButtonPromeni))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCitalac)
                    .addComponent(jButtonPromeniCitaoca)
                    .addComponent(jComboBoxCitaoci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSacuvajCitaoca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonObrisi)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPromeni)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPromeniCitaocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniCitaocaActionPerformed
        jComboBoxCitaoci.setEnabled(true);
    }//GEN-LAST:event_jButtonPromeniCitaocaActionPerformed

    private void jButtonSacuvajCitaocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajCitaocaActionPerformed
        Citalac izabraniCitalac = (Citalac) jComboBoxCitaoci.getSelectedItem();
        if(izabraniCitalac.equals(citalac)){
            return;
        }
        
        System.out.println("PRE IZMENE : " + iznajmljivanje.getCitalac().getId());
        iznajmljivanje.setCitalac(izabraniCitalac);
        System.out.println("POSLE IZMENE : " + iznajmljivanje.getCitalac().getId());
        int affectedRows = Controller.getInstance().promeniIznajmljivanje(iznajmljivanje);
        if(affectedRows != 0){
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste izmenili citaoca za izabrano iznajmljivanje");
            return;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sistem nije uspesno izmenio citaoca za izabrano iznajmljivanje");
            return;
        }
    }//GEN-LAST:event_jButtonSacuvajCitaocaActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int selektovaniRed = jTable.getSelectedRow();
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati stavku iz tabele", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        StavkaIznajmljivanja selektovanaStavka = modelTabele.getListaStavki().get(selektovaniRed);
        int rowsAffected = Controller.getInstance().obrisiStavku(selektovanaStavka);
        if(rowsAffected != 0){
            JOptionPane.showMessageDialog(this, "Stavka je uspesno obrisana", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Stavka nije uspesno obrisana", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        modelTabele.deleteStavka(selektovaniRed);
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniActionPerformed
        int selektovaniRed = jTable.getSelectedRow();
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati stavku iz tabele", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        StavkaIznajmljivanja selektovanaStavka = modelTabele.getListaStavki().get(selektovaniRed);
        DetaljiStavka dialogDetaljiStavka = new DetaljiStavka(this, rootPaneCheckingEnabled, iznajmljivanje, selektovanaStavka);
        dialogDetaljiStavka.setVisible(true);
        
        modelTabele.updateStavka(selektovaniRed);
    }//GEN-LAST:event_jButtonPromeniActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPromeni;
    private javax.swing.JButton jButtonPromeniCitaoca;
    private javax.swing.JButton jButtonSacuvajCitaoca;
    private javax.swing.JComboBox<Citalac> jComboBoxCitaoci;
    private javax.swing.JLabel jLabelCitalac;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

    private void podesiTabelu(ModelTabeleStavkaIzn modelTabele) {
        jTable.setModel(modelTabele);
        jTable.setRowSelectionAllowed(true);
        jTable.setColumnSelectionAllowed(false);
        jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // dogadjaj - odselektovanja reda
        jTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTable.rowAtPoint(e.getPoint());

                if (row == poslednjeSelektRed) {
                    jTable.clearSelection();
                    poslednjeSelektRed = -1;
                } else {
                    poslednjeSelektRed = row;
                }
            }
        });
    }

    private void popuniComboboxCitaoci() {
        List<Citalac> listaCitaoca = Controller.getInstance().vratiSveCitaoce();
        jComboBoxCitaoci.removeAllItems();
        Citalac selektovani = null;
        
        for (Citalac c : listaCitaoca) {
            jComboBoxCitaoci.addItem(c);
            if(c.equals(citalac)){
                selektovani = c;
            }
        }
        jComboBoxCitaoci.setSelectedItem(selektovani);
        jComboBoxCitaoci.setEnabled(false);
    }
}