/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import model.Iznajmljivanje;
import model.StavkaIznajmljivanja;

/**
 *
 * @author lukaa
 */
public class DetaljiStavka extends javax.swing.JDialog {

    private Iznajmljivanje iznajmljivanje;
    private StavkaIznajmljivanja stavka;
    /**
     * Creates new form DetaljiStavka
     */
    public DetaljiStavka(java.awt.Frame parent, boolean modal, Iznajmljivanje iznajmljivanje, StavkaIznajmljivanja stavka) {
        super(parent, modal);
        initComponents();
        this.iznajmljivanje = iznajmljivanje;
        this.stavka = stavka;
        
        jTextFieldBrojDana.setText(stavka.getBrojDana() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBrojDana = new javax.swing.JTextField();
        jButtonPotvrdi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Stavka Iznajmljivanja");

        jLabel3.setText("Broj dana:");

        jButtonPotvrdi.setText("Potvrdi");
        jButtonPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotvrdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonPotvrdi)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonPotvrdi)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotvrdiActionPerformed
        String brojDanaStr = jTextFieldBrojDana.getText();
        int brojDana;
        try{
            brojDana = Integer.parseInt(brojDanaStr);
            if(brojDana <= 0){
                JOptionPane.showMessageDialog(null, "Broj dana mora biti veći od 0");
                return;
            }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Broj dana mora biti ceo broj");
            return;
        }
        
        LocalDate datumUzimanja = iznajmljivanje.getDatumUzimanja();
        LocalDate datumVracanja = datumUzimanja.plusDays(brojDana);
        stavka.setDatumVracanja(datumVracanja);
        stavka.setBrojDana(brojDana);
        
        System.out.println("Pre poziva kontrolera");
        int affectedRows = Controller.getInstance().promeniStavku(stavka);
        System.out.println("Nakon poziva kontrolera");
        if(affectedRows != 0){
            JOptionPane.showMessageDialog(this, "Stavka je uspesno promenjena");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Stavka nije uspesno promenjena");
            this.dispose();
        }
    }//GEN-LAST:event_jButtonPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPotvrdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldBrojDana;
    // End of variables declaration//GEN-END:variables
}
