/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.JOptionPane;
import model.Bibliotekar;
import form.mods.ModPretraziCitalac;
import session.Session;
/**
 *
 * @author lukaa
 */
public class GlavnaForma extends javax.swing.JFrame {
    
    private Bibliotekar ulogovaniBibliotekar;
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        try{
            setLocationRelativeTo(null);
            initComponents();
            ulogovaniBibliotekar = Session.getInstance().getUlogovaniKorisnik();
            jLabel1.setText(ulogovaniBibliotekar.toString());
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Ne moze da se otvori glavna forma i meni", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuIznajmljivanje = new javax.swing.JMenu();
        jMenuItemKreirajIzn = new javax.swing.JMenuItem();
        jMenuItemPretraziIzn = new javax.swing.JMenuItem();
        jMenuCitalac = new javax.swing.JMenu();
        jMenuItemKreirajCitaoca = new javax.swing.JMenuItem();
        jMenuItemPretraziCitaoca = new javax.swing.JMenuItem();
        jMenuRadnaSmena = new javax.swing.JMenu();
        jMenuItemUbaciRadnuSmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zdravo");

        jMenuIznajmljivanje.setText("Iznajmljivanje");

        jMenuItemKreirajIzn.setText("Kreiraj Iznajmljivanje");
        jMenuItemKreirajIzn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajIznActionPerformed(evt);
            }
        });
        jMenuIznajmljivanje.add(jMenuItemKreirajIzn);

        jMenuItemPretraziIzn.setText("Pretrazi Iznajmljivanje");
        jMenuIznajmljivanje.add(jMenuItemPretraziIzn);

        jMenuBar.add(jMenuIznajmljivanje);

        jMenuCitalac.setText("Citalac");

        jMenuItemKreirajCitaoca.setText("Kreiraj Citaoca");
        jMenuItemKreirajCitaoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajCitaocaActionPerformed(evt);
            }
        });
        jMenuCitalac.add(jMenuItemKreirajCitaoca);

        jMenuItemPretraziCitaoca.setText("Pretrazi Citaoca");
        jMenuItemPretraziCitaoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziCitaocaActionPerformed(evt);
            }
        });
        jMenuCitalac.add(jMenuItemPretraziCitaoca);

        jMenuBar.add(jMenuCitalac);

        jMenuRadnaSmena.setText("Radna Smena");

        jMenuItemUbaciRadnuSmenu.setText("Ubaci");
        jMenuRadnaSmena.add(jMenuItemUbaciRadnuSmenu);

        jMenuBar.add(jMenuRadnaSmena);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKreirajIznActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajIznActionPerformed
        PretraziCitalac formaKreirajIzn = new PretraziCitalac(ModPretraziCitalac.IZNAJMLJIVANJE);
        formaKreirajIzn.pack();
        formaKreirajIzn.setLocationRelativeTo(null);
        formaKreirajIzn.setVisible(true);
    }//GEN-LAST:event_jMenuItemKreirajIznActionPerformed

    private void jMenuItemKreirajCitaocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajCitaocaActionPerformed
        PodaciCitalac dialogKreirajCitaoca = new PodaciCitalac(this, true, null);
        dialogKreirajCitaoca.pack();
        dialogKreirajCitaoca.setLocationRelativeTo(null);
        dialogKreirajCitaoca.setVisible(true);
    }//GEN-LAST:event_jMenuItemKreirajCitaocaActionPerformed

    private void jMenuItemPretraziCitaocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziCitaocaActionPerformed
        PretraziCitalac formaPretraziCitaoca = new PretraziCitalac(ModPretraziCitalac.STANDARD);
        formaPretraziCitaoca.pack();
        formaPretraziCitaoca.setLocationRelativeTo(null);
        formaPretraziCitaoca.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretraziCitaocaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCitalac;
    private javax.swing.JMenuItem jMenuItemKreirajCitaoca;
    private javax.swing.JMenuItem jMenuItemKreirajIzn;
    private javax.swing.JMenuItem jMenuItemPretraziCitaoca;
    private javax.swing.JMenuItem jMenuItemPretraziIzn;
    private javax.swing.JMenuItem jMenuItemUbaciRadnuSmenu;
    private javax.swing.JMenu jMenuIznajmljivanje;
    private javax.swing.JMenu jMenuRadnaSmena;
    // End of variables declaration//GEN-END:variables
}
