/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import model.Knjiga;
import model.Zanr;
import controller.Controller;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.Autor;
import model.Citalac;
import model.Iznajmljivanje;
import model.StavkaIznajmljivanja;
import modeliTabele.ModelTabeleKnjige;
import modeliTabele.ModelTabeleStavkaIzn;
import session.Session;

/**
 *
 * @author lukaa
 */
public class KreirajIznajmljivanje extends javax.swing.JDialog {

    private ModelTabeleKnjige modelTabeleKnjige;
    private ModelTabeleStavkaIzn modelTabeleStavka;
    private Citalac citalac;
    private double ukupnaCena = 0;
    /**
     * Creates new form FormaKreirajIznajmljivanje
     */
    public KreirajIznajmljivanje(Citalac selektovaniCitalac) {
        initComponents();
        ucitajComboboxAutori();
        ucitajComboboxZanrovi();
        citalac = selektovaniCitalac;
        jTextFieldUkupnaCena.setEditable(false);
        
        this.modelTabeleKnjige = new ModelTabeleKnjige();
        List<Knjiga> listaKnjiga = Controller.getInstance().vratiSveKnjige();
        
        jTableKnjige.setModel(modelTabeleKnjige);
        this.modelTabeleStavka = new ModelTabeleStavkaIzn();
        jTableStavke.setModel(modelTabeleStavka);
        
        podesiTabelu(jTableKnjige);
        podesiTabelu(jTableStavke);
        
        modelTabeleKnjige.setLista(listaKnjiga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxZanr = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKnjige = new javax.swing.JTable();
        jButtonDodajKnjigu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jButtonKreirajIzn = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUkupnaCena = new javax.swing.JTextField();
        jComboBoxAutor = new javax.swing.JComboBox<>();
        jButtonPonistiFiltere = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Iznajmljivanje");

        jLabel2.setText("Izaberite knjigu koju zelite dodati:");

        jLabel3.setText("Naziv:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Zanr:");

        jButtonPretrazi.setText("Pretrazi knjigu");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTableKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKnjige);

        jButtonDodajKnjigu.setText("Dodaj knjigu");
        jButtonDodajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajKnjiguActionPerformed(evt);
            }
        });

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableStavke);

        jButtonKreirajIzn.setText("Kreiraj Iznajmljivanje");
        jButtonKreirajIzn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajIznActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jLabel6.setText("Cena:");

        jButtonPonistiFiltere.setText("Ponisti filtere");
        jButtonPonistiFiltere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPonistiFiltereActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonKreirajIzn))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonObrisi)
                            .addComponent(jButtonIzmeni)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNaziv)
                                    .addComponent(jComboBoxAutor, 0, 168, Short.MAX_VALUE)
                                    .addComponent(jComboBoxZanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPonistiFiltere)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPretrazi)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(404, 404, 404)
                                .addComponent(jButtonDodajKnjigu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPonistiFiltere)
                            .addComponent(jButtonPretrazi)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDodajKnjigu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonObrisi)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIzmeni)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKreirajIzn)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        String naziv = jTextFieldNaziv.getText();
        Autor autor = (Autor) jComboBoxAutor.getSelectedItem();
        Zanr zanr = (Zanr) jComboBoxZanr.getSelectedItem();
        
        System.out.println(naziv + " " + autor + " " + zanr);
        
        List<Autor> listaAutora = null;
        if(autor != null) {
            listaAutora = new ArrayList<>();
            listaAutora.add(autor);
        }
        
        Knjiga filter = new Knjiga();
        filter.setNaziv(naziv);
        filter.setAutori(listaAutora);
        filter.setZanr(zanr);
        
        List<Knjiga> listaKnjiga = Controller.getInstance().pretraziKnjigu(filter);
        modelTabeleKnjige.setLista(listaKnjiga);
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonDodajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajKnjiguActionPerformed
        int selektovaniRed = jTableKnjige.getSelectedRow();
        
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati knjigu koju želite dodati", "Greška", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Knjiga selektovanaKnjiga = modelTabeleKnjige.getRow(selektovaniRed);
        for (StavkaIznajmljivanja stavka : modelTabeleStavka.getListaStavki()) {
            if(stavka.getKnjiga().getId() == selektovanaKnjiga.getId()){
                JOptionPane.showMessageDialog(this, "Izabrana knjiga je već dodata u listu", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                jTableKnjige.clearSelection();
                return;
            }
        }
        
        String unos = JOptionPane.showInputDialog(this, "Unesite broj dana:");
        if (unos == null) return;
        int brojDana;
        try {
            brojDana = Integer.parseInt(unos);
            if (brojDana <= 0) throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unesite validan broj dana!");
            return;
        }
        
        System.out.println("IZABRANA KNJIGA JE: " + selektovanaKnjiga);
        StavkaIznajmljivanja stavka = new StavkaIznajmljivanja();
        LocalDate datumUzimanja = LocalDate.now();
        LocalDate datumVracanja = datumUzimanja.plusDays(brojDana);
        
        stavka.setDatumVracanja(datumVracanja);
        stavka.setBrojDana(brojDana);
        stavka.setIznosPoDanu(selektovanaKnjiga.getIznosPoDanu());
        stavka.setIznos(selektovanaKnjiga.getIznosPoDanu()*brojDana);
        stavka.setValuta("DIN");
        stavka.setKnjiga(selektovanaKnjiga);
        
        modelTabeleStavka.addStavka(stavka);
        jTableKnjige.clearSelection();
        
        ukupnaCena += stavka.getIznos();
        jTextFieldUkupnaCena.setText(ukupnaCena + " DIN");
    }//GEN-LAST:event_jButtonDodajKnjiguActionPerformed

    private void jButtonKreirajIznActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajIznActionPerformed
        Iznajmljivanje iznajmljivanje = new Iznajmljivanje();
        
        int brojKnjiga = modelTabeleStavka.getListaStavki().size();
        LocalDate datumUzimanja = LocalDate.now();
        double ukupanIznos = 0;
        for (StavkaIznajmljivanja s : modelTabeleStavka.getListaStavki()) {
            ukupanIznos += s.getIznos();
        }
        
        iznajmljivanje.setBrojKnjiga(brojKnjiga);
        iznajmljivanje.setDatumUzimanja(datumUzimanja);
        iznajmljivanje.setUkupanIznos(ukupanIznos);
        iznajmljivanje.setValuta("DIN");
        iznajmljivanje.setBibliotekar(Session.getInstance().getUlogovaniKorisnik());
        iznajmljivanje.setCitalac(citalac);
        iznajmljivanje.setListaStavki(modelTabeleStavka.getListaStavki());
        System.out.println("Broj stavki: " + iznajmljivanje.getListaStavki().size());
        
        int uspesnoKreiranoIznajmljivanje = Controller.getInstance().kreirajIznajmljivanje(iznajmljivanje);
        if(uspesnoKreiranoIznajmljivanje != -1){
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio iznajmljivanje", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti iznajmljivanje", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonKreirajIznActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int selektovaniRed = jTableStavke.getSelectedRow();
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati stavku koju želite izbaciti", "Greška", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        StavkaIznajmljivanja selektovanaStavka = modelTabeleStavka.getListaStavki().get(selektovaniRed);
        ukupnaCena -= selektovanaStavka.getIznos();
        jTextFieldUkupnaCena.setText(ukupnaCena + " DIN");
        modelTabeleStavka.deleteStavka(selektovaniRed);
        jTableStavke.clearSelection();
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonPonistiFiltereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPonistiFiltereActionPerformed
        jTextFieldNaziv.setText("");
        jComboBoxZanr.setSelectedItem(null);
        jComboBoxAutor.setSelectedItem(null);
        
        List<Knjiga> listaKnjiga = Controller.getInstance().vratiSveKnjige();
        modelTabeleKnjige.setLista(listaKnjiga);
    }//GEN-LAST:event_jButtonPonistiFiltereActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        int selektovaniRed = jTableStavke.getSelectedRow();
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati stavku iz tabele", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        StavkaIznajmljivanja selektovanaStavka = modelTabeleStavka.getListaStavki().get(selektovaniRed);
        
        String unos = JOptionPane.showInputDialog(this, "Unesite broj dana:");
        if (unos == null) return;
        int brojDana;
        try {
            brojDana = Integer.parseInt(unos);
            if (brojDana <= 0) throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unesite validan broj dana!");
            return;
        }
        
        double novi_iznos = selektovanaStavka.getIznosPoDanu() * brojDana;
        
        LocalDate datumUzimanja = LocalDate.now();
        LocalDate datumVracanja = datumUzimanja.plusDays(brojDana);
        
        ukupnaCena -= selektovanaStavka.getIznos();
        modelTabeleStavka.getListaStavki().get(selektovaniRed).setBrojDana(brojDana);
        modelTabeleStavka.getListaStavki().get(selektovaniRed).setIznos(novi_iznos);
        modelTabeleStavka.getListaStavki().get(selektovaniRed).setDatumVracanja(datumVracanja);
        ukupnaCena += modelTabeleStavka.getListaStavki().get(selektovaniRed).getIznos();
        
        jTextFieldUkupnaCena.setText(ukupnaCena + "");
        modelTabeleStavka.fireTableDataChanged();
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajKnjigu;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreirajIzn;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPonistiFiltere;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JComboBox<Autor> jComboBoxAutor;
    private javax.swing.JComboBox<Zanr> jComboBoxZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableKnjige;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldUkupnaCena;
    // End of variables declaration//GEN-END:variables

    private void ucitajComboboxZanrovi() {
        jComboBoxZanr.removeAllItems();
        for(Zanr z : Zanr.values()){
            jComboBoxZanr.addItem(z);
        }
        jComboBoxZanr.setSelectedItem(null);
    }
    
    private void ucitajComboboxAutori() {
        jComboBoxAutor.removeAllItems();
        List<Autor> listaAutora = new ArrayList<>();
        listaAutora = Controller.getInstance().vratiSveAutore();
        for (Autor autor : listaAutora) {
            jComboBoxAutor.addItem(autor);
        }
        jComboBoxAutor.setSelectedItem(null);
    }

    private void podesiTabelu(JTable tabela) {
        // 1. Dozvoli samo jedan selektovani red
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabela.setRowSelectionAllowed(true);
        tabela.setColumnSelectionAllowed(false);

        // 2. Omogući deselect klikom na isti red
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            private int lastSelectedRow = -1;

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                int row = tabela.rowAtPoint(e.getPoint());

                if (row == lastSelectedRow) {
                    tabela.clearSelection();
                    lastSelectedRow = -1;
                } else {
                    lastSelectedRow = row;
                }
            }
        });
    }
}