/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import model.Knjiga;
import model.Zanr;
import controller.Controller;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.Citalac;
import model.Iznajmljivanje;
import model.StavkaIznajmljivanja;
import modeliTabele.ModelTabeleKnjige;
import modeliTabele.ModelTabeleStavkaIzn;
import session.Session;

/**
 *
 * @author lukaa
 */
public class KreirajIznajmljivanje extends javax.swing.JDialog {

    private ModelTabeleKnjige modelTabeleKnjige;
    private ModelTabeleStavkaIzn modelTabeleIznajmljivanje;
    private Citalac citalac;
    /**
     * Creates new form FormaKreirajIznajmljivanje
     */
    public KreirajIznajmljivanje(Citalac selektovaniCitalac) {
        initComponents();
        ucitajCombobox();
        citalac = selektovaniCitalac;
        
        this.modelTabeleKnjige = new ModelTabeleKnjige();
        jTableKnjige.setModel(modelTabeleKnjige);
        this.modelTabeleIznajmljivanje = new ModelTabeleStavkaIzn();
        jTableIznajmljivanje.setModel(modelTabeleIznajmljivanje);
        
        podesiTabelu(jTableKnjige);
        podesiTabelu(jTableIznajmljivanje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKnjige = new javax.swing.JTable();
        jButtonDodajKnjigu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableIznajmljivanje = new javax.swing.JTable();
        jButtonKreirajIzn = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Iznajmljivanje");

        jLabel2.setText("Izaberite knjigu koju zelite dodati:");

        jLabel3.setText("Naziv:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Zanr:");

        jButtonPretrazi.setText("Pretrazi knjigu");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTableKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKnjige);

        jButtonDodajKnjigu.setText("Dodaj knjigu");
        jButtonDodajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajKnjiguActionPerformed(evt);
            }
        });

        jTableIznajmljivanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableIznajmljivanje);

        jButtonKreirajIzn.setText("Kreiraj Iznajmljivanje");
        jButtonKreirajIzn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajIznActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonKreirajIzn)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonPretrazi)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNaziv)
                                        .addComponent(jTextFieldAutor)
                                        .addComponent(jComboBox, 0, 106, Short.MAX_VALUE))))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDodajKnjigu))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPretrazi)
                            .addComponent(jButtonDodajKnjigu)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonKreirajIzn)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        String naziv = jTextFieldNaziv.getText();
        String autor = jTextFieldAutor.getText();
        Zanr zanr = (Zanr) jComboBox.getSelectedItem();
        
        Knjiga filter = new Knjiga();
        filter.setNaziv(naziv);
        filter.setAutor(autor);
        filter.setZanr(zanr);
        
        List<Knjiga> listaKnjiga = Controller.getInstance().pretraziKnjigu(filter);
        modelTabeleKnjige.setLista(listaKnjiga);
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonDodajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajKnjiguActionPerformed
        int selektovaniRed = jTableKnjige.getSelectedRow();
        
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati knjigu koju zelite dodati", "Greska", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Knjiga selektovanaKnjiga = modelTabeleKnjige.getRow(selektovaniRed);
        if(modelTabeleIznajmljivanje.getListaStavki().contains(selektovanaKnjiga)){
            JOptionPane.showMessageDialog(this, "Izabrana knjiga je vec dodata u listu", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String unos = JOptionPane.showInputDialog(this, "Unesite broj dana:");
        if (unos == null) return;
        int brojDana;
        try {
            brojDana = Integer.parseInt(unos);
            if (brojDana <= 0) throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unesite validan broj dana!");
            return;
        }
        
        System.out.println("IZABRANA KNJIGA JE: " + selektovanaKnjiga);
        StavkaIznajmljivanja stavka = new StavkaIznajmljivanja();
        LocalDate datumUzimanja = LocalDate.now();
        LocalDate datumVracanja = datumUzimanja.plusDays(brojDana);
        
        stavka.setDatumVracanja(datumVracanja);
        stavka.setBrojDana(brojDana);
        stavka.setIznosPoDanu(selektovanaKnjiga.getIznosPoDanu());
        stavka.setIznos(selektovanaKnjiga.getIznosPoDanu()*brojDana);
        stavka.setValuta("DIN");
        stavka.setKnjiga(selektovanaKnjiga);
        
        modelTabeleIznajmljivanje.addStavka(stavka);
        jTableKnjige.clearSelection();
    }//GEN-LAST:event_jButtonDodajKnjiguActionPerformed

    private void jButtonKreirajIznActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajIznActionPerformed
        Iznajmljivanje iznajmljivanje = new Iznajmljivanje();
        
        int brojKnjiga = modelTabeleIznajmljivanje.getListaStavki().size();
        LocalDate datumUzimanja = LocalDate.now();
        double ukupanIznos = 0;
        for (StavkaIznajmljivanja s : modelTabeleIznajmljivanje.getListaStavki()) {
            ukupanIznos += s.getIznos();
        }
        
        iznajmljivanje.setBrojKnjiga(brojKnjiga);
        iznajmljivanje.setDatumUzimanja(datumUzimanja);
        iznajmljivanje.setUkupanIznos(ukupanIznos);
        iznajmljivanje.setValuta("DIN");
        iznajmljivanje.setBibliotekar(Session.getInstance().getUlogovaniKorisnik());
        iznajmljivanje.setCitalac(citalac);
        iznajmljivanje.setListaStavki(modelTabeleIznajmljivanje.getListaStavki());
        System.out.println("Broj stavki: " + iznajmljivanje.getListaStavki().size());
        
        int uspesnoKreiranoIznajmljivanje = Controller.getInstance().kreirajIznajmljivanje(iznajmljivanje);
        if(uspesnoKreiranoIznajmljivanje != -1){
            JOptionPane.showMessageDialog(this, "Uspesno ste kreirali iznajmljivanje", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Greska. Iznajmljivanje nije uspesno kreirano", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonKreirajIznActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajKnjigu;
    private javax.swing.JButton jButtonKreirajIzn;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JComboBox<Zanr> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableIznajmljivanje;
    private javax.swing.JTable jTableKnjige;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    private void ucitajCombobox() {
        jComboBox.removeAllItems();
        for(Zanr z : Zanr.values()){
            jComboBox.addItem(z);
        }
        jComboBox.setSelectedItem(null);
    }

    private void podesiTabelu(JTable tabela) {
        // 1. Dozvoli samo jedan selektovani red
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabela.setRowSelectionAllowed(true);
        tabela.setColumnSelectionAllowed(false);

        // 2. Omogući deselect klikom na isti red
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            private int lastSelectedRow = -1;

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                int row = tabela.rowAtPoint(e.getPoint());

                if (row == lastSelectedRow) {
                    tabela.clearSelection();
                    lastSelectedRow = -1;
                } else {
                    lastSelectedRow = row;
                }
            }
        });
    }
}
