/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Citalac;
import model.Kategorija;
import model.KategorijaCitaoca;
import form.mods.ModPodaciCitalac;

/**
 *
 * @author lukaa
 */
public class PodaciCitalac extends javax.swing.JDialog {
    
    private boolean izmenjeno = false;
    private Citalac citalacZaIzmenu;
    private ModPodaciCitalac mod = null;
    /**
     * Creates new form KreirajCitaoca
     */
    public PodaciCitalac(java.awt.Frame parent, boolean modal, Citalac selektovaniCitalac) {
        super(parent, modal);
        citalacZaIzmenu = selektovaniCitalac;
        if(selektovaniCitalac == null){
            mod = ModPodaciCitalac.KREIRAJ;
        } else {
            mod = ModPodaciCitalac.PROMENI;
        }
        
        initComponents();
        ucitajComboBox();
        setLocationRelativeTo(parent);
        
        if(mod == ModPodaciCitalac.PROMENI){
            jButtonObrisi.setVisible(true);
            jTextFieldIme.setText(citalacZaIzmenu.getIme());
            jTextFieldPrezime.setText(citalacZaIzmenu.getPrezime());
            jTextFieldEmail.setText(citalacZaIzmenu.getEmail());
            jTextFieldTelefon.setText(citalacZaIzmenu.getTelefon());
            
            for (int i = 0; i < jComboBox.getItemCount(); i++) {
                KategorijaCitaoca k = jComboBox.getItemAt(i);
                if (k.getId() == citalacZaIzmenu.getKategorija().getId()) {
                    jComboBox.setSelectedIndex(i);
                    break;
                }
            }
        } else if(mod == ModPodaciCitalac.KREIRAJ){
            jButtonObrisi.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jButtonPotvrdi = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Citalac");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabel5.setText("Telefon:");

        jLabel6.setText("Kategorija:");

        jButtonPotvrdi.setText("Potvrdi");
        jButtonPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotvrdiActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonObrisi)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPotvrdi))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldEmail)
                                .addComponent(jTextFieldPrezime)
                                .addComponent(jTextFieldTelefon)
                                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPotvrdi)
                    .addComponent(jButtonObrisi))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotvrdiActionPerformed
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        String email = jTextFieldEmail.getText();
        String telefon = jTextFieldTelefon.getText();
        KategorijaCitaoca kategorija = (KategorijaCitaoca) jComboBox.getSelectedItem();
        
        
        if(mod == ModPodaciCitalac.KREIRAJ){
            // provera validnosti unetih podataka
            if (!ime.matches("[a-zA-ZšđčćžŠĐČĆŽ]+")) {
                System.out.println("Ime nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!prezime.matches("[a-zA-ZšđčćžŠĐČĆŽ]+")) {
                System.out.println("Prezime nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!email.contains("@")) {
                System.out.println("Email nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!telefon.matches("\\+3816\\d{4,8}")) {
                System.out.println("Telefon nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(jComboBox.getSelectedItem() == null){
                System.out.println("Nije selektovana kategorija citaoca");
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // kreiranje citaoca i ubacivanje u bazu
            Citalac citalac = new Citalac(0, ime, prezime, email, telefon, kategorija);
            
            int generatedId = Controller.getInstance().kreirajCitaoca(citalac);
            if(generatedId != -1){
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio čitaoca", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti čitaoca", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else if(mod == ModPodaciCitalac.PROMENI){
            // provera validnosti unetih podataka
            if (!ime.matches("[a-zA-ZšđčćžŠĐČĆŽ]+")) {
                System.out.println("Ime nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!prezime.matches("[a-zA-ZšđčćžŠĐČĆŽ]+")) {
                System.out.println("Prezime nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!email.contains("@")) {
                System.out.println("Email nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!telefon.matches("\\+3816\\d{4,8}")) {
                System.out.println("Telefon nije u dobrom formatu");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(jComboBox.getSelectedItem() == null){
                System.out.println("Nije selektovana kategorija citaoca");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti čitaoca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            citalacZaIzmenu.setIme(ime);
            citalacZaIzmenu.setPrezime(prezime);
            citalacZaIzmenu.setEmail(email);
            citalacZaIzmenu.setTelefon(telefon);
            citalacZaIzmenu.setKategorija(kategorija);
            
            int affectedRows = Controller.getInstance().promeniCitaoca(citalacZaIzmenu);
            if(affectedRows == 1){
                izmenjeno = true;
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio čitaoca.", "Uspesna izmena", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti čitaoca.", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_jButtonPotvrdiActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        // pitanje za korisnika, da li je siguran da zeli da obrise citaoca
        int potvrda = JOptionPane.showConfirmDialog(
        this, 
        "Da li ste sigurni da želite da obrišete čitaoca?", 
        "Potvrda brisanja", 
        JOptionPane.YES_NO_OPTION
        );

        if(potvrda != JOptionPane.YES_OPTION){
            return;
        }
    
        // brisanje citaoca
        int rowsAffected = Controller.getInstance().obrisiCitaoca(citalacZaIzmenu);
        if(rowsAffected == 1){
            JOptionPane.showMessageDialog(this, "Sistem je obrisao čitaoca.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše čitaoca.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPotvrdi;
    private javax.swing.JComboBox<KategorijaCitaoca> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    // End of variables declaration//GEN-END:variables

    private void ucitajComboBox() {
        jComboBox.removeAllItems();
        List<KategorijaCitaoca> listaKategorija = Controller.getInstance().vratiSveKategorije();
        for (KategorijaCitaoca kategorija : listaKategorija) {
            jComboBox.addItem(kategorija);
        }
        jComboBox.setSelectedItem(null);
    }
    
    public boolean isIzmenjeno(){
        return izmenjeno;
    }
}