/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import modeliTabele.ModelTabeleCitalac;
import controller.Controller;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Citalac;
import model.Kategorija;
import model.KategorijaCitaoca;
import form.mods.ModPretraziCitalac;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import model.Bibliotekar;
import model.Iznajmljivanje;
import modeliTabele.ModelTabeleIznajmljivanje;

/**
 *
 * @author lukaa
 */
public class PretraziIznajmljivanje extends javax.swing.JFrame {

    ModelTabeleIznajmljivanje modelTabele;
    /**
     * Creates new form KreirajCitaoca
     */
    public PretraziIznajmljivanje() {
        setLocationRelativeTo(null);
        initComponents();
        ucitajComboBoxCitaoci();
        ucitajComboBoxBibliotekari();
        
        ModelTabeleIznajmljivanje modelTabele = new ModelTabeleIznajmljivanje();
        jTable.setModel(modelTabele);
        jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable.setRowSelectionAllowed(true);
        jTable.setColumnSelectionAllowed(false);
        this.modelTabele = modelTabele;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelCitalac = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDatumDo = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jComboBoxCitaoci = new javax.swing.JComboBox<>();
        jComboBoxBibliotekari = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIznos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBrojKnjiga = new javax.swing.JTextField();
        jButtonDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Iznajmljivanje");

        jLabelCitalac.setText("Citalac:");

        jLabel3.setText("Bibliotekar:");

        jLabel5.setText("Datum do:");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel2.setText("Maksimalan iznos:");

        jLabel4.setText("Maksimalan broj knjiga:");

        jButtonDetalji.setText("Detalji");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCitalac, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxBibliotekari, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCitaoci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPretrazi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBrojKnjiga))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDetalji))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCitalac)
                            .addComponent(jComboBoxCitaoci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxBibliotekari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldBrojKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDetalji))
                .addGap(18, 18, 18)
                .addComponent(jButtonPretrazi)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        Citalac citalac = (Citalac) jComboBoxCitaoci.getSelectedItem();
        Bibliotekar bibliotekar = (Bibliotekar) jComboBoxBibliotekari.getSelectedItem();
        String datumDo = jTextFieldDatumDo.getText();
        LocalDate datum = null;
        if(datumDo != null && !datumDo.isEmpty()){
            try {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
                datum = LocalDate.parse(jTextFieldDatumDo.getText(), formatter);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Neispravan format datuma!");
                return;
            }
        }
        
        String iznosStr = jTextFieldIznos.getText().trim();
        double iznos = 0;
        if (!iznosStr.isEmpty()) {
            try {
                iznosStr = iznosStr.replace(",", ".");
                iznos = Double.parseDouble(iznosStr);
                if(iznos == 0.0){
                    JOptionPane.showMessageDialog(null, "Uneti broj knjiga ne sme biti 0");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Uneti broj knjiga nije validan!");
                return;
            }
        }
        
        String brojKnjigaStr = jTextFieldBrojKnjiga.getText().trim();
        int brojKnjiga = 0;
        if (!brojKnjigaStr.isEmpty()) {
            try {
                brojKnjiga = Integer.parseInt(brojKnjigaStr);
                if(brojKnjiga == 0){
                    JOptionPane.showConfirmDialog(null, "Uneti broj knjiga ne sme biti 0");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Uneti broj knjiga nije validan!");
                jTextFieldBrojKnjiga.requestFocus();
                return;
            }
        }
        
        Iznajmljivanje filterIzn = new Iznajmljivanje();
        filterIzn.setCitalac(citalac);
        filterIzn.setBibliotekar(bibliotekar);
        filterIzn.setDatumUzimanja(datum);
        filterIzn.setUkupanIznos(iznos);
        filterIzn.setBrojKnjiga(brojKnjiga);
        
        List<Iznajmljivanje> listaIznajmljivanja = Controller.getInstance().pretraziIznajmljivanje(filterIzn);
        modelTabele.setListaIznajmljivanja(listaIznajmljivanja);
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int selektovaniRed = jTable.getSelectedRow();
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati red iz tabele", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Iznajmljivanje iznajmljivanje = modelTabele.getListaIznajmljivanja().get(selektovaniRed);
        DetaljiIznajmljivanje formaDetaljiIzn = new DetaljiIznajmljivanje(iznajmljivanje);
        formaDetaljiIzn.setVisible(true);
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JComboBox<Bibliotekar> jComboBoxBibliotekari;
    private javax.swing.JComboBox<Citalac> jComboBoxCitaoci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCitalac;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldBrojKnjiga;
    private javax.swing.JTextField jTextFieldDatumDo;
    private javax.swing.JTextField jTextFieldIznos;
    // End of variables declaration//GEN-END:variables

    private void ucitajComboBoxCitaoci() {
        jComboBoxCitaoci.removeAllItems();
        List<Citalac> listaCitalaca = Controller.getInstance().vratiSveCitaoce();
        for (Citalac citalac : listaCitalaca) {
            jComboBoxCitaoci.addItem(citalac);
        }
        jComboBoxCitaoci.setSelectedItem(null);
    }

    private void ucitajComboBoxBibliotekari() {
        jComboBoxBibliotekari.removeAllItems();
        List<Bibliotekar> listaBibliotekara = Controller.getInstance().vratiSveBibliotekare();
        for (Bibliotekar bibliotekar : listaBibliotekara) {
            jComboBoxBibliotekari.addItem(bibliotekar);
            System.out.println(bibliotekar);
        }
        jComboBoxBibliotekari.setSelectedItem(null);
    }
}