/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import modeliTabele.ModelTabeleCitalac;
import controller.Controller;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Citalac;
import model.Kategorija;
import model.KategorijaCitaoca;
import form.mods.ModPretraziCitalac;
import javax.swing.SwingUtilities;

/**
 *
 * @author lukaa
 */
public class PretraziCitalac extends javax.swing.JFrame {

    private ModPretraziCitalac mod;
    private ModelTabeleCitalac modelTabele;
    private Citalac selektovaniCitalac;
    private Citalac filter;
    private int poslednjeSelektRed = -1;
    /**
     * Creates new form KreirajCitaoca
     */
    public PretraziCitalac(ModPretraziCitalac mod) {
        this.mod = mod;
        setLocationRelativeTo(null);
        initComponents();
        ucitajComboBox();
        
        modelTabele = new ModelTabeleCitalac();
        List<Citalac> listaSvihCitalaca = Controller.getInstance().vratiSveCitaoce();
        modelTabele.setLista(listaSvihCitalaca);
        
        jTable.setModel(modelTabele);
        jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable.setRowSelectionAllowed(true);
        jTable.setColumnSelectionAllowed(false);
        
        // dogadjaj - odselektovanja reda
        jTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTable.rowAtPoint(e.getPoint());

                if (row == poslednjeSelektRed) {
                    jTable.clearSelection();
                    selektovaniCitalac = null;
                    poslednjeSelektRed = -1;
                } else {
                    poslednjeSelektRed = row;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxKategorija = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonKreirajIzn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Čitalac");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabel5.setText("Telefon:");

        jLabel6.setText("Kategorija:");

        jButtonPretrazi.setText("Pretraži");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jButtonKreirajIzn.setText("Kreiraj Iznajmljivanje");
        jButtonKreirajIzn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajIznActionPerformed(evt);
            }
        });

        jLabel7.setText("Pretraga čitalaca po filterima");

        jButtonDetalji.setText("Detalji");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPretrazi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldEmail)
                                .addComponent(jTextFieldPrezime)
                                .addComponent(jTextFieldTelefon)
                                .addComponent(jComboBoxKategorija, 0, 134, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKreirajIzn)
                    .addComponent(jButtonDetalji))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDetalji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKreirajIzn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonPretrazi)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        filter = null;
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        String email = jTextFieldEmail.getText();
        String telefon = jTextFieldTelefon.getText();
        KategorijaCitaoca kategorija = (KategorijaCitaoca) jComboBoxKategorija.getSelectedItem();
        
        // provera validnosti unetih podataka
        if (!ime.isEmpty() && !ime.matches("[a-zA-ZšđčćžŠĐČĆŽ]+")) {
            System.out.println("Ime nije u dobrom formatu");
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe čitaoce po zadatim kriterijumima.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!prezime.isEmpty() && !prezime.matches("[a-zA-ZšđčćžŠĐČĆŽ]+")) {
            System.out.println("Prezime nije u dobrom formatu");
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe čitaoce po zadatim kriterijumima.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!email.isEmpty() && !email.contains("@")) {
            System.out.println("Email nije u dobrom formatu");
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe čitaoce po zadatim kriterijumima.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!telefon.isEmpty() && !telefon.matches("\\+3816\\d{4,8}")) {
            System.out.println("Telefon nije u dobrom formatu");
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe čitaoce po zadatim kriterijumima.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Citalac citalac = new Citalac(0, ime, prezime, email, telefon, kategorija);
        filter = citalac;
        List<Citalac> listaCitalaca = Controller.getInstance().pretraziCitaoca(filter);
        modelTabele.setLista(listaCitalaca);
        
        JOptionPane.showMessageDialog(this, "Sistem je našao čitaoce po zadatim kriterijumima", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonKreirajIznActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajIznActionPerformed
        int selektovaniRed = jTable.getSelectedRow();
        
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati red iz tabele ", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ModelTabeleCitalac model = (ModelTabeleCitalac) jTable.getModel();
        selektovaniCitalac = model.getRow(selektovaniRed);
        
        KreirajIznajmljivanje dialogKreirajIzn = new KreirajIznajmljivanje(selektovaniCitalac);
        dialogKreirajIzn.pack();
        dialogKreirajIzn.setLocationRelativeTo(null);
        dialogKreirajIzn.setVisible(true);
    }//GEN-LAST:event_jButtonKreirajIznActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int selektovaniRed = jTable.getSelectedRow();
        if(selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe čitaoca.", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        } else{
            JOptionPane.showMessageDialog(this, "Sistem je našao čitaoca.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        }
        
        ModelTabeleCitalac model = (ModelTabeleCitalac) jTable.getModel();
        selektovaniCitalac = model.getRow(selektovaniRed);
        
        PodaciCitalac dialogPromeniCitaoca = new PodaciCitalac(this, true, selektovaniCitalac);
        dialogPromeniCitaoca.setVisible(true);

        // nakon zatvaranja forme, ocisti polja za filtriranje i osvezi tabelu
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelefon.setText("");
        jComboBoxKategorija.setSelectedItem(null);
        
        List<Citalac> listaCitalaca = Controller.getInstance().vratiSveCitaoce();
        modelTabele.setLista(listaCitalaca);    
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonKreirajIzn;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JComboBox<KategorijaCitaoca> jComboBoxKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    // End of variables declaration//GEN-END:variables

    private void ucitajComboBox() {
        jComboBoxKategorija.removeAllItems();
        List<KategorijaCitaoca> listaKategorija = Controller.getInstance().vratiSveKategorije();
        for (KategorijaCitaoca kategorija : listaKategorija) {
            jComboBoxKategorija.addItem(kategorija);
        }
        jComboBoxKategorija.setSelectedItem(null);
    }
}