/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import javax.swing.JOptionPane;
import model.RadnaSmena;
import model.Smena;

/**
 *
 * @author lukaa
 */
public class UbaciRadnuSmenu extends javax.swing.JDialog {

    /**
     * Creates new form UbaciRadnuSmenu
     */
    public UbaciRadnuSmenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniComboboxNaziv();
        popuniComboboxTrajanje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxNaziv = new javax.swing.JComboBox<>();
        jComboBoxTrajanje = new javax.swing.JComboBox<>();
        jButtonPotvrdi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Radna Smena");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Trajanje:");

        jButtonPotvrdi.setText("Potvrdi");
        jButtonPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotvrdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPotvrdi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxNaziv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxTrajanje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonPotvrdi)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotvrdiActionPerformed
        Smena naziv = (Smena) jComboBoxNaziv.getSelectedItem();
        String trajanjeStr = (String) jComboBoxTrajanje.getSelectedItem();
        int trajanje = Integer.parseInt(trajanjeStr.replace("h", ""));
        
        RadnaSmena radnaSmena = new RadnaSmena();
        radnaSmena.setNaziv(naziv);
        radnaSmena.setTrajanje(trajanje);
        
        int key = Controller.getInstance().ubaciRadnuSmenu(radnaSmena);
        if(key != 0){
            JOptionPane.showMessageDialog(rootPane, "Sistem je zapamtio radnu smenu");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sistem ne moze da zapamti radnu smenu");
        }
        
        this.dispose();
    }//GEN-LAST:event_jButtonPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPotvrdi;
    private javax.swing.JComboBox<Smena> jComboBoxNaziv;
    private javax.swing.JComboBox<String> jComboBoxTrajanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void popuniComboboxNaziv() {
        jComboBoxNaziv.removeAllItems();
        for (Smena smena : Smena.values()) {
            jComboBoxNaziv.addItem(smena);
        }
    }

    private void popuniComboboxTrajanje() {
        jComboBoxTrajanje.removeAllItems();
        for (int i = 1; i <= 12; i++) {
            jComboBoxTrajanje.addItem(i + "h");
        }
    }
}